# The Fibonacci animation (the textbooks' Maths chapter 10, and a loading splash): writes the squares and
# the spiral into its row of data/textbooks.json from the sequence itself. Run: python3 tools/fib.py
#
# ASKED FOR AS "make fibonacci sequence animation smaller so can fit more of it in". It drew five
# squares, 1 1 2 3 5, at eight units a side; this draws EIGHT, 1 1 2 3 5 8 13 21, at two units, in
# the same box on the screen. The ratio of the tiling goes 1.600 -> 1.619, which is the point of the
# picture: the more of the sequence, the nearer the golden ratio.
#
# LAID OUT BY RULE, NOT BY HAND. Each square goes against the whole of what came before, turning
# down, left, up, right, and the arc in each runs from the corner it shares with the last square to
# the opposite corner about the corner that makes it a clockwise quarter turn. The script asserts
# what the old hand-made one had to learn the hard way: every arc starts where the last one ended,
# and the heading is continuous at every joint, so it is a spiral and not a rosette.
import math, re, pathlib
import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent)); import anim_row

F = [1, 1, 2, 3, 5, 8, 13, 21]
U = 2.0                                   # units per Fibonacci 1
M = 4.0                                   # margin round the tiling

def build(off, start):
    """The tiling turned `off` quarter-steps round, and the spiral from corner `start` of the first
    square. Raises AssertionError if the chain is not a tangent spiral."""
    sq = [(0, 0, 1)]
    x0 = y0 = 0; x1 = y1 = 1
    dirs = ['down', 'left', 'up', 'right']
    for k, s in enumerate(F[1:]):
        d = dirs[(k + off) % 4]
        if d == 'down':   assert x1 - x0 == s; sq.append((x0, y1, s)); y1 += s
        elif d == 'left': assert y1 - y0 == s; sq.append((x0 - s, y0, s)); x0 -= s
        elif d == 'up':   assert x1 - x0 == s; sq.append((x0, y0 - s, s)); y0 -= s
        else:             assert y1 - y0 == s; sq.append((x1, y0, s)); x1 += s
    arcs, heading_out = [], None
    for (x, y, s) in sq:
        cs = corners(x, y, s)
        assert start in cs, 'the spiral left square %s' % ((x, y, s),)
        i = cs.index(start); end = cs[(i + 2) % 4]
        ok = []
        for c in [(start[0], end[1]), (end[0], start[1])]:
            a0 = math.atan2(start[1] - c[1], start[0] - c[0]); a1 = math.atan2(end[1] - c[1], end[0] - c[0])
            if abs(((a1 - a0) % (2 * math.pi)) - math.pi / 2) < 1e-9: ok.append((a0, a1))
        assert len(ok) == 1
        a0, a1 = ok[0]
        h_in = (a0 + math.pi / 2) % (2 * math.pi); h_out = (a1 + math.pi / 2) % (2 * math.pi)
        if heading_out is not None:
            assert abs(((h_in - heading_out + math.pi) % (2 * math.pi)) - math.pi) < 1e-9, 'a cusp'
        heading_out = h_out
        arcs.append((start, end, s)); start = end
    return sq, arcs, (x0, y0, x1, y1)

def corners(x, y, s): return [(x, y), (x + s, y), (x + s, y + s), (x, y + s)]

# LANDSCAPE, LIKE THE ONE IT REPLACES, and the first layout that is a true tangent spiral.
found = None
for off in range(4):
    for st in corners(0, 0, 1):
        try:
            sq, arcs, bb = build(off, st)
        except AssertionError:
            continue
        if bb[2] - bb[0] > bb[3] - bb[1]:
            found = (sq, arcs, bb); break
    if found: break
assert found, 'no landscape tangent spiral'
sq, arcs, (x0, y0, x1, y1) = found
W, H = (x1 - x0) * U + 2 * M, (y1 - y0) * U + 2 * M
P = lambda x, y: ((x - x0) * U + M, (y - y0) * U + M)

f = lambda v: ('%.2f' % v).rstrip('0').rstrip('.')
rects = '\n'.join('      <rect class="fb-sq" style="--i:%d" x="%s" y="%s" width="%s" height="%s"/>'
                  % ((k,) + tuple(f(v) for v in P(x, y)) + (f(s * U), f(s * U))) for k, (x, y, s) in enumerate(sq))
sx, sy = P(*arcs[0][0])
d = 'M%s %s ' % (f(sx), f(sy)) + ' '.join('A%s %s 0 0 1 %s %s' % ((f(s * U), f(s * U)) + tuple(f(v) for v in P(*e)))
                                          for (_, e, s) in arcs)
length = sum(math.pi / 2 * s * U for s in F)
svg = '''<svg class="fb-svg" viewBox="0 0 %s %s">
      <!-- GENERATED by tools/fib.py from the sequence %s: each square laid against the whole of
           what came before, and one clockwise quarter turn in each, checked for tangency at every
           joint. Edit the script, not this. -->
%s
      <path class="fb-arc" d="%s"/>
    </svg>''' % (f(W), f(H), ' '.join(map(str, F)), rects, d)

# INTO ITS ROW IN data/textbooks.json, not index.html — see tools/anim_row.py.
anim_row.write_anim('fib', fragments=[svg, '<div class="fb-say">%s</div>' % ' '.join(map(str, F))])
print('viewBox %s x %s, %d squares, ratio %.3f, arc length %.1f' % (f(W), f(H), len(sq), (x1 - x0) / (y1 - y0), length))
