# The index-laws splash (#splash-index): writes the <div> into index.html and the rules and
# @keyframes into style.css, from the one timeline below. Run: python3 tools/index.py
#
# WHAT IT SHOWS, in one loop of T seconds: a·a·a × a·a. The two groups close up and the × goes with
# them; then, while they are joined, the five tiles are counted 1, 2, 3, 4, 5 — a numeral under each
# as it lights — and a⁵ is written in the sum when the fifth is counted. Then the count clears, the
# groups part, the × comes back, and it starts again from exactly where it began.
#
# WHY IT IS GENERATED, when the old one was four hand-written lines. Measured on the old one:
#  · TWO CLOCKS. The tiles lit on a 4s cycle delayed 1.6s + 0.22s each, and the groups joined on
#    the same 4s with no delay — so the lights ran from 3.44s to 5.04s while the groups were only
#    together from 1.76s to 4.0s. The last two tiles lit after the groups had parted again, with
#    the × back on screen between them. Counting is only an argument while they are joined, so here
#    every window is worked out from ONE list of times and the script asserts the count sits
#    inside the join.
#  · A SNAP AT THE SEAM. The join and the × had no return leg: at 100% → 0% the second group jumped
#    22px right and the × popped in, in one frame. Every keyframe here ends on its 0% value.
#  · THE WRONG GAP. Only the second group moved, by a fixed 1.5rem that ignored the ×'s width, so
#    the joined row had 1.1px between tiles 3 and 4 against 4.4px everywhere else and sat 11px left
#    of centre. Now the distance is the gap either side of the × plus the × minus the gap between
#    tiles — all four are custom properties, and each group moves half of it, towards the other.
#  · THE ANSWER FROM THE FIRST FRAME. "a⁵" was in the caption before anything had been counted.
# Transform and opacity only. The base styles are the joined, counted row — what reduced motion shows.
import re, pathlib
import sys; sys.path.insert(0, str(__import__('pathlib').Path(__file__).resolve().parent)); import anim_row

T = 6.0                         # seconds, one loop
CLOSE = (0.5, 1.2)              # the groups slide together
X_OUT = (0.5, 0.9)              # and the × fades as they do
COUNT0, COUNT_STEP = 1.4, 0.4   # tile k is counted at COUNT0 + (k-1)·COUNT_STEP
LIGHT = 0.15                    # how long one light takes to come up
CLEAR = (4.3, 4.6)              # the count, the numerals and a⁵ go, together
OPEN = (4.6, 5.3)               # then the groups part
X_IN = (4.9, 5.3)               # and the × comes back
GROUPS = (3, 2)                 # a³ × a²

N = sum(GROUPS)
counted = [COUNT0 + k * COUNT_STEP for k in range(N)]
# THE WHOLE POINT, asserted: every tile is counted while the two groups are joined, and the count is
# held long enough to read before it clears.
assert CLOSE[1] < counted[0], 'a tile is counted before the groups have joined'
assert counted[-1] + LIGHT < CLEAR[0] - 0.8, 'five is not held long enough to read'
assert CLEAR[1] <= OPEN[0], 'the groups part while the count is still showing'
assert X_OUT[0] >= CLOSE[0] and X_IN[1] <= OPEN[1] and OPEN[1] < T

def pct(t): return ('%.2f' % (100 * t / T)).rstrip('0').rstrip('.') + '%'

def lit(name, on):
    # dark, up at `on`, held, down with the rest. 0% and 100% are the same: no seam.
    return ('@keyframes %s { 0%%, %s { opacity: 0; } %s, %s { opacity: 1; } %s, 100%% { opacity: 0; } }'
            % (name, pct(on), pct(on + LIGHT), pct(CLEAR[0]), pct(CLEAR[1])))

# ---- the markup -----------------------------------------------------------------------------------
tiles, k = [], 0
for g, n in enumerate(GROUPS):
    cells = []
    for _ in range(n):
        k += 1
        cells.append('<i class="ix-t%d">a<b class="ix-n">%d</b></i>' % (k, k))
    tiles.append('<span class="ix-g ix-g%d">%s</span>' % (g + 1, ''.join(cells)))
h = ['<div id="splash-index" aria-hidden="true">',
     '    <!-- GENERATED by tools/index.py — edit the timeline there, not here. -->',
     '    <div class="ix-line">',
     '      ' + tiles[0],
     '      <span class="ix-op">&times;</span>',
     '      ' + tiles[1],
     '    </div>',
     '    <div class="ix-say">a<sup>%d</sup> &times; a<sup>%d</sup> = <span class="ix-sum">a<sup>%d</sup></span></div>'
     % (GROUPS[0], GROUPS[1], N),
     '    <div class="sp-sig">@family.</div>',
     '  </div>']
markup = '\n'.join(h)

# ---- the rules ------------------------------------------------------------------------------------
lights = '\n'.join(lit('ix-lit-%d' % (i + 1), counted[i]) for i in range(N))
per_tile = '\n'.join('.ix-t%d::after, .ix-t%d .ix-n { animation: ix-lit-%d %gs ease-out infinite; }' % (i + 1, i + 1, i + 1, T)
                     for i in range(N))
css = f'''/* ---------- INDEX LAWS ---------------------------------------------------------------------------
   GENERATED by tools/index.py, from one list of times — what was wrong before, and why each piece is
   the way it is, is written there.

   THE TWO GROUPS CLOSE UP AND THE × GOES OUT WITH THEM, because the whole claim of the law is that
   three a's and two a's are five a's — a thing that happens, not a thing that is. Then, while they
   are joined, the five are counted, a numeral under each, and a⁵ is written when the fifth is. The
   count clears, the groups part, and the loop ends on its first frame.

   THE JOIN IS EXACT. Open, the groups are --ix-out from the × on each side and the × is --ix-op
   wide; joined, tiles 3 and 4 must be --ix-in apart like every other pair. So the gap closes by
   2·out + op − in, and each group moves HALF of it towards the other — the joined row is evenly
   spaced and keeps the open row's centre. The old one moved only the second group by a fixed 1.5rem:
   1.1px between tiles 3 and 4 against 4.4px elsewhere, and 11px left of centre.

   The base styles are the joined, counted row with a⁵ written — what reduced motion shows. */
#splash-index {{ --ix-in: .3rem; --ix-out: .5rem; --ix-op: 1rem;
                --ix-shift: calc((2 * var(--ix-out) + var(--ix-op) - var(--ix-in)) / 2); }}
/* ROOM UNDER THE ROW FOR THE NUMERALS, which hang below their tiles rather than in the flow, so
   counting never moves anything. */
.ix-line {{ display: flex; align-items: center; justify-content: center; gap: var(--ix-out);
           padding-bottom: 1.1rem; }}
.ix-g {{ display: flex; gap: var(--ix-in); }}
.ix-g i {{ position: relative; display: grid; place-items: center; width: 2rem; height: 2rem;
          border-radius: 6px; background: #2a2c27; border: 2px solid #3c4038; color: var(--paper);
          font: 700 .95rem var(--mono); font-style: normal; }}
/* THE LIGHT IS A RING OVER THE TILE THAT FADES, not the tile's border changing colour: a colour is
   repainted by the main thread, which is busy parsing the app at exactly this moment, and opacity
   is the compositor's. */
.ix-g i::after {{ content: ""; position: absolute; inset: -2px; border: 2px solid var(--gold);
                 border-radius: 6px; }}
.ix-n {{ position: absolute; top: calc(100% + .3rem); left: 0; right: 0; text-align: center;
        font: 700 .7rem/1 var(--mono); color: var(--gold); }}
.ix-op {{ width: var(--ix-op); text-align: center; color: var(--paper); font: 700 1rem var(--mono);
         opacity: 0; animation: ix-op {T:g}s ease-in-out infinite; }}
@keyframes ix-op {{ 0%, {pct(X_OUT[0])} {{ opacity: 1; }} {pct(X_OUT[1])}, {pct(X_IN[0])} {{ opacity: 0; }}
                   {pct(X_IN[1])}, 100% {{ opacity: 1; }} }}
.ix-g1 {{ transform: translateX(var(--ix-shift)); animation: ix-g1 {T:g}s ease-in-out infinite; }}
.ix-g2 {{ transform: translateX(calc(-1 * var(--ix-shift))); animation: ix-g2 {T:g}s ease-in-out infinite; }}
@keyframes ix-g1 {{ 0%, {pct(CLOSE[0])} {{ transform: translateX(0); }} {pct(CLOSE[1])}, {pct(OPEN[0])} {{ transform: translateX(var(--ix-shift)); }}
                   {pct(OPEN[1])}, 100% {{ transform: translateX(0); }} }}
@keyframes ix-g2 {{ 0%, {pct(CLOSE[0])} {{ transform: translateX(0); }} {pct(CLOSE[1])}, {pct(OPEN[0])} {{ transform: translateX(calc(-1 * var(--ix-shift))); }}
                   {pct(OPEN[1])}, 100% {{ transform: translateX(0); }} }}
/* COUNTED ONE AT A TIME, all cleared together — so five is reached, held, and let go at once. */
{per_tile}
{lights}
.ix-say {{ margin-top: .5rem; font: 700 .9rem var(--mono); color: var(--paper); text-align: center; }}
/* a⁵ IS WRITTEN WHEN THE FIFTH TILE IS COUNTED, and not before. */
.ix-sum {{ color: var(--gold); animation: ix-lit-{N} {T:g}s ease-out infinite; }}
@media (prefers-reduced-motion: reduce) {{
  .ix-op, .ix-g1, .ix-g2, .ix-sum {{ animation: none; }}
{chr(10).join('  .ix-t%d::after, .ix-t%d .ix-n { animation: none; }' % (i + 1, i + 1) for i in range(N))}
}}

'''

# INTO ITS ROW IN data/textbooks.json, not index.html and style.css — see tools/anim_row.py.
anim_row.write_anim('index', html=markup, css=css)
print('%d tiles counted at %s s, joined %.1f-%.1f s, loop %gs'
      % (N, ', '.join('%.1f' % t for t in counted), CLOSE[1], OPEN[0], T))
