# The unit-circle animation (the textbooks' Maths chapter 7, and a loading splash): writes the <svg> and
# the rules and @keyframes into its row of data/textbooks.json, both from one set of numbers, through
# tools/anim_row.py. This script is the row's source: change it here and re-run, never the row.
# Run: python3 tools/sine.py
#
# The x axis of the wave IS the circle unrolled: one period is 2*pi*R long, so a point a distance d
# to the right of where the wave leaves the circle shows the height the dot had d/R radians ago.
# The wave is one fixed path that slides right by exactly one period per turn, so the loop has no
# seam, and everything that moves moves by transform. The un-animated geometry is the frame at
# THETA0, which is what prefers-reduced-motion shows.
import math, re, pathlib
import sys; sys.path.insert(0, str(__import__('pathlib').Path(__file__).resolve().parent)); import anim_row
T = 4.0                          # seconds per turn
R, CX, CY = 18.0, 24.0, 34.0     # the circle
X0, XR = 52.0, 176.0             # where the wave leaves the circle, and where it fades out
THETA0 = math.pi / 3             # the still frame: 60 degrees
P = 2 * math.pi * R              # one period, the circumference
N = 72                           # keyframe steps, 5 degrees each

def h(th): return CY - R * math.sin(th)               # height of the dot at angle th
def f(v): return ('%.2f' % v).rstrip('0').rstrip('.') if abs(v) >= .005 else '0'

# the wave at the still frame: y(x) = height the dot had (x - X0)/R radians before THETA0.
# drawn from one period left of X0 so it can slide right by P and land on itself.
pts, x = [], X0 - P
while x <= XR + 0.01:
    pts.append('%s %s' % (f(x), f(h(THETA0 - (x - X0) / R))))
    x += 1.0
wave = 'M' + ' L'.join(pts)

dx0, dy0 = CX + R * math.cos(THETA0), h(THETA0)       # the dot, still
glen0 = X0 - dx0                                        # guide length, still
s0 = math.sin(THETA0)

svg = f'''<svg class="sn-svg" viewBox="0 0 180 68">
      <!-- GENERATED by tools/sine.py — edit the numbers there, not here. The wave's x axis is the
           circle unrolled (one period = 2&#960;r), and the wave slides right one period per turn. -->
      <defs>
        <linearGradient id="sn-fade" x1="{f(X0)}" x2="{f(XR)}" gradientUnits="userSpaceOnUse">
          <stop offset="0" stop-color="#fff"/><stop offset=".78" stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity="0"/>
        </linearGradient>
        <mask id="sn-mask" maskUnits="userSpaceOnUse" x="0" y="0" width="180" height="68">
          <rect x="{f(X0)}" y="0" width="{f(XR - X0)}" height="68" fill="url(#sn-fade)"/>
        </mask>
      </defs>
      <line class="sn-axis" x1="{f(CX - R - 4)}" y1="{f(CY)}" x2="{f(XR)}" y2="{f(CY)}"/>
      <circle class="sn-ring" cx="{f(CX)}" cy="{f(CY)}" r="{f(R)}"/>
      <g mask="url(#sn-mask)"><path class="sn-wave" d="{wave}"/></g>
      <line class="sn-guide" x1="{f(dx0)}" y1="{f(dy0)}" x2="{f(X0)}" y2="{f(dy0)}"/>
      <line class="sn-leg" x1="{f(dx0)}" y1="{f(CY)}" x2="{f(dx0)}" y2="{f(dy0)}"/>
      <line class="sn-arm" x1="{f(CX)}" y1="{f(CY)}" x2="{f(dx0)}" y2="{f(dy0)}"/>
      <circle class="sn-dot" cx="{f(dx0)}" cy="{f(dy0)}" r="3"/>
      <circle class="sn-trace" cx="{f(X0)}" cy="{f(dy0)}" r="2.6"/>
    </svg>'''

guide, leg, trace = [], [], []
for i in range(N + 1):
    p = i / N
    th = THETA0 + 2 * math.pi * p
    pc = '%.4g%%' % (100 * p)
    dy = h(th) - dy0
    k = (X0 - (CX + R * math.cos(th))) / glen0
    guide.append(f'{pc} {{ transform: translateY({f(dy)}px) scaleX({k:.4f}); }}')
    leg.append(f'{pc} {{ transform: translateX({f(R * (math.cos(th) - math.cos(THETA0)))}px) scaleY({math.sin(th) / s0:.4f}); }}')
    trace.append(f'{pc} {{ transform: translateY({f(dy)}px); }}')

css = f'''/* ---------- THE UNIT CIRCLE AND THE SINE WAVE ---------------------------------------------------
   GENERATED by tools/sine.py, from the same numbers as the <svg> beside it in the row.

   The dot goes round anticlockwise (negative rotation, because SVG's y axis points down) and its
   height is carried across by the dashed guide to where the wave leaves the circle. The wave's x
   axis is the circle UNROLLED — one period is 2πr — so the wave is the dot's own history, and it
   slides right by exactly one period per turn, which is why the loop has no seam. The teal leg
   inside the circle is sin θ drawn where it lives. Everything moves by transform and nothing by
   `stroke-dashoffset`, which repainted the path every frame. The un-animated geometry is the frame
   at θ = 60°, so reduced motion shows a finished picture rather than a dot sitting on the axis. */
#splash-sine .sn-svg {{ width: min(76vw, 18rem); max-width: 100%; height: auto; overflow: visible; }}
.sn-ring, .sn-axis {{ fill: none; stroke: rgb(244 241 232 / .3); stroke-width: 1.1; }}
.sn-wave {{ fill: none; stroke: #6fd8c4; stroke-width: 2; stroke-linecap: round;
           animation: sn-roll {T:g}s linear infinite; }}
@keyframes sn-roll {{ to {{ transform: translateX({f(P)}px); }} }}
.sn-arm {{ stroke: #f0b45f; stroke-width: 1.6; stroke-linecap: round;
          transform-origin: {f(CX)}px {f(CY)}px; animation: sn-spin {T:g}s linear infinite; }}
.sn-dot {{ fill: #f0b45f; transform-origin: {f(CX)}px {f(CY)}px; animation: sn-spin {T:g}s linear infinite; }}
@keyframes sn-spin {{ to {{ transform: rotate(-360deg); }} }}
.sn-guide {{ stroke: rgb(240 180 95 / .45); stroke-width: 1; stroke-dasharray: 2 2;
            transform-origin: {f(X0)}px {f(dy0)}px; animation: sn-guide {T:g}s linear infinite; }}
.sn-leg {{ stroke: #6fd8c4; stroke-width: 1.6; stroke-linecap: round;
          transform-origin: {f(dx0)}px {f(CY)}px; animation: sn-leg {T:g}s linear infinite; }}
.sn-trace {{ fill: #6fd8c4; animation: sn-trace {T:g}s linear infinite; }}
@keyframes sn-guide {{ {' '.join(guide)} }}
@keyframes sn-leg {{ {' '.join(leg)} }}
@keyframes sn-trace {{ {' '.join(trace)} }}
'''

# INTO ITS ROW IN data/textbooks.json, not index.html and style.css — see tools/anim_row.py.
anim_row.write_anim('sine', fragments=[svg], css=css)
print('period %.2f, %d wave points, %d keyframes' % (P, len(pts), N + 1))
