# The solar system (the textbooks' Physics chapter 12, "Space physics", and a loading splash): writes
# the <div> and the rules and @keyframes into its row of data/textbooks.json, both from the one table
# below, through tools/anim_row.py. Run: python3 tools/solar.py
#
# IT WAS ONE OF THE "CALM ONES THAT TEACH NOTHING" and stayed in index.html and style.css when the
# teaching animations moved into the books (docs/history/304). It teaches a law: every planet turns
# in its real period, T proportional to a^1.5, which is Kepler's third law and the reason the inner
# ones lap the outer ones — what Physics chapter 12 says as "a faster satellite needs a smaller
# orbit". So it moved too, under "Solar system". The two inline styles it wrote became custom
# properties (`--t` the period, `--o` the ring's pivot): a drawing in a book sets custom properties
# and nothing else inline, because an inline declaration beats the reduced-motion rule.
#
# ORDER AND PERIODS ARE REAL, RADII ARE NOT. Each period is Kepler's third law off the planet's
# real semi-major axis (T proportional to a^1.5, in years), then every one is multiplied by EARTH_S
# so Earth goes round in a few seconds — the RATIOS are untouched, which is why Mercury laps four
# times while Earth goes once and Neptune barely moves. The radii are evenly spaced instead of true,
# because at true scale the four inner planets are a smudge beside the Sun and Neptune is off the
# phone. Sizes are ordered like the real ones and nothing more.
#
# Each planet is drawn at its own starting angle and its group turns about the Sun, so every orbit
# is its own seamless loop and the un-animated geometry is a finished picture — which is what
# prefers-reduced-motion shows. Everything moves by `transform: rotate` and nothing else.
import math, re, pathlib
import sys; sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent)); import anim_row

EARTH_S = 4.0                  # seconds for one Earth year
C = 60.0                       # the Sun, centre of a 120 x 120 viewBox
R0, DR = 11.0, 6.4             # first orbit, and the step between orbits
#          name       a (AU)  size  colour     start angle (deg, 0 = right, anticlockwise)
PLANETS = [('mercury', 0.387, 1.6, '#b8b0a4', 200),
           ('venus',   0.723, 2.3, '#e8cf9a', 35),
           ('earth',   1.000, 2.4, '#6fa8dc', 250),
           ('mars',    1.524, 1.9, '#e0714a', 120),
           ('jupiter', 5.203, 4.2, '#d9a877', 310),
           ('saturn',  9.537, 3.3, '#e6c98a', 150),
           ('uranus',  19.19, 2.8, '#9fe0dc', 20),
           ('neptune', 30.07, 2.7, '#6f8fea', 230)]

def f(v): return ('%.2f' % v).rstrip('0').rstrip('.') if abs(v) >= .005 else '0'

orbits, bodies, rules = [], [], []
for i, (name, a, size, col, deg) in enumerate(PLANETS):
    r = R0 + i * DR
    th = math.radians(deg)
    x, y = C + r * math.cos(th), C - r * math.sin(th)   # SVG y points down
    period = EARTH_S * a ** 1.5
    orbits.append(f'<circle class="or-path" cx="{f(C)}" cy="{f(C)}" r="{f(r)}"/>')
    inner = f'<circle cx="{f(x)}" cy="{f(y)}" r="{f(size)}" fill="{col}"/>'
    if name == 'saturn':
        # the ring is counter-rotated about the planet, so it keeps its tilt all the way round
        # instead of turning with the orbit
        # the back half of the ring goes behind the planet and the front half across it
        rx, ry = size * 2, size * .62
        def arc(sweep):
            return (f'<g class="or-ring" style="--o: {f(x)}px {f(y)}px">'
                    f'<path d="M{f(x - rx)} {f(y)} A{f(rx)} {f(ry)} 0 0 {sweep} {f(x + rx)} {f(y)}" '
                    f'transform="rotate(-20 {f(x)} {f(y)})"/></g>')
        inner = arc(1) + inner + arc(0)
    bodies.append(f'<g class="or-p or-{name}" style="--t: {period:.2f}s">{inner}</g>')
    rules.append(f'/* {name}: a = {a} AU, T = {a ** 1.5:.3f} yr -> {period:.2f}s */')
    if name == 'saturn':
        saturn = period

svg = f'''<div id="splash-orbit" aria-hidden="true">
    <svg class="or-svg" viewBox="0 0 120 120">
      <!-- GENERATED by tools/solar.py — edit the table there, not here. Real order, real period
           ratios (Kepler, T proportional to a^1.5), orbit radii evenly spaced so all eight fit. -->
      <defs>
        <radialGradient id="or-glow"><stop offset="0" stop-color="#f0b45f" stop-opacity=".55"/><stop offset="1" stop-color="#f0b45f" stop-opacity="0"/></radialGradient>
      </defs>
      {chr(10).join('      ' + o for o in orbits).lstrip()}
      <circle cx="{f(C)}" cy="{f(C)}" r="10" fill="url(#or-glow)"/>
      <circle class="or-sun" cx="{f(C)}" cy="{f(C)}" r="4.6"/>
      {chr(10).join('      ' + b for b in bodies).lstrip()}
    </svg>
    <div class="sp-sig">@family.</div>
  </div>'''

css = f'''/* ---------- A SOLAR SYSTEM ----------------------------------------------------------------------------
   GENERATED by tools/solar.py, from the same table as the <svg> beside it in the row.

   The eight planets in their real order, each going round in its real period relative to the
   others — Kepler's third law, T ∝ a^1.5, off the real semi-major axes — with Earth's year taken as
   {EARTH_S:g}s. So Mercury laps about four times per Earth year and Neptune turns a degree or two while
   the app loads, which is the solar system rather than a decoration of one. The orbit RADII are
   evenly spaced rather than true, so all eight fit and the inner four are not a smudge on the Sun.
   Each planet is drawn at its own starting angle and its group turns about the Sun, anticlockwise as
   seen from above the north pole, so every loop is seamless and the still geometry is a finished
   picture; Saturn's ring counter-turns about the planet so it keeps its tilt. Transform only. */
{chr(10).join(rules)}
/* `max-width: 100%` as well as the phone's 64vw: a chapter's card is narrower than the phone. */
#splash-orbit .or-svg {{ display: block; width: min(64vw, 11rem); max-width: 100%; height: auto; margin: 0 auto; overflow: visible; }}
.or-path {{ fill: none; stroke: rgb(244 241 232 / .13); stroke-width: .45; }}
.or-sun {{ fill: #f0b45f; }}
.or-p {{ transform-origin: {f(C)}px {f(C)}px; animation: or-turn var(--t) linear infinite; }}
.or-ring {{ transform-origin: var(--o); animation: or-back {saturn:.2f}s linear infinite; }}
.or-ring path {{ fill: none; stroke: #e6c98a; stroke-width: .7; opacity: .8; }}
@keyframes or-turn {{ to {{ transform: rotate(-360deg); }} }}
@keyframes or-back {{ to {{ transform: rotate(360deg); }} }}
/* The still is the drawn geometry: every planet at its own starting angle, Saturn's ring tilted. */
@media (prefers-reduced-motion: reduce) {{
  .or-p, .or-ring {{ animation: none; opacity: 1; transform: none; }}
}}

'''

# INTO ITS ROW IN data/textbooks.json, not index.html and style.css — see tools/anim_row.py.
anim_row.write_anim('orbit', html=svg, css=css)
print('Earth %gs, Mercury %.2fs, Neptune %.1fs' % (EARTH_S, EARTH_S * .387 ** 1.5, EARTH_S * 30.07 ** 1.5))
